# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: mmistakes/so-simple-theme
title: Thuleanx
name: An Nguyen
email: thuleanx@tutanota.com
description: >- # this means to ignore newlines until "baseurl:"
  Game developer | Graphics programmer 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/logo.png"
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
  - name: "Barlow"
    weights: "400,400i,700,700i"
  - name: "Prata"
    weights: "400,400i,700,700i"
read_time: false
words_per_minute: 200
date_format: "%Y-%m-%d"
skin: "/assets/css/skins/custom.css"

# Build settings
markdown: kramdown
locale: en-US
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-include-cache
  - jekyll-archives

include: ["_pages"]


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

atom_feed:
  hide: true
search: true
timezone: America/New_York

author:
  name: "Thuleanx"
  picture: "/assets/images/logo.png"
  email: "thuleanx@tutanota.com"

footer_links:
  - title: "Itch"
    url: "https://thuleanx.itch.io/"
    icon: "fab fa fa-gamepad"
  - title: "GitHub"
    url: "https://github.com/thuleanx"
    icon: "fab fa-fw fa-github"
  - title: "Twitter"
    url: "https://twitter.com/neuthalz"
    icon: "fab fa-fw fa-twitter-square"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      show_date: true
      date_format: "%Y-%m-%d"
  # _games
  - scope:
      path: ""
      type: games
    values:
      layout: post
      author_profile: false
      classes: wide
  # _graphics
  - scope:
      path: ""
      type: graphics
    values:
      layout: post
      author_profile: false
      classes: wide

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/

collections:
  graphics:
    output: true
    permalink: /:collection/:path/
  games:
    output: true
    permalink: /:collection/:path/
